# Generated by Django 5.2.11 on 2026-06-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = []
