# Generated by Django 4.2.30 on 2026-05-03 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200)),
                ('shop_slug', models.SlugField(blank=True, unique=True)),
                ('shop_description', models.TextField(blank=True)),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='shops/')),
                ('shop_banner', models.ImageField(blank=True, null=True, upload_to='shop_banners/')),
                ('category_focus', models.CharField(blank=True, help_text='Type de produits vendus', max_length=200)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('suspended', 'Suspendu')], default='pending', max_length=15)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Vendeur',
                'verbose_name_plural': 'Profils Vendeurs',
                'ordering': ['-is_featured', '-total_sales'],
            },
        ),
    ]
